### PR TITLE
Allow protobuf export to idiomatic Go

### PR DESCRIPTION
**Pull request by zeevallin**
Thanks for making this library, it's a really good initiative and I would like to contribute by adding some support for exporting to Go.

Currently I only added support to the `compile_single.py` script as it is already reading the contents of the files and modifying the temporary intermediary. If we want to add support for the recursive compilation, we would also have to create temporary files that can be interpreted and modified before running through `protoc`.

I hope at least these few changes are alright!

### CODE REVIEW

**Comment by rastapasta** [comment]
Cloned and ran with different params, got no errors while testing, so it's good to go i think :-)
Thank's for your work + contribution!

**Comment by pxue** [comment]
hey sorry for pulling this up after it's closed. is there a reason why the proto are compiled to separate packages? @zeeraw 
it's screwing with my build and vendoring

**Comment by zeevallin** [comment]
Hey @pxue, I couldn't get protoc to compile if they were all combined in one package. I would get conflicts. If you have any ideas of how it could all be compiled to one package, that would be cool. Personally I would also like to get the recursive compilation working to have a 1:1 mapping between the proto & go packages.

**Comment by pxue** [comment]
ah okay. Yes, the Go work around is to pass all proto files as to the protoc command. ie,

`protoc --proto_path=tmp --go_out=out tmp/*.proto`

that'll allow you to compile all proto files under the package specified with `option go_package`

**Pull request merged**
