### PR TITLE
Add compile_pretty.py

### PR DESCRIPTION
**Pull request by ghost**
This compile script creates very pretty output. It ...
- ... produces language-specific output.
- ... respects naming conventions of the language.
- ... generates correct namespaces/package names.
- ... generates __init__.py and require helpers for Ruby for simple import statements.
- ... rewrites the .proto files to have the same path, package and file name as the generated code.
- ... generates a .desc file.
- ... provides compile options for Java and C++.
- ... supports pretty output for C++, C#, Go, Java, JavaScript, Objective C, Python and Ruby.

> usage: compile_pretty.py [-h] [-p PROTOC_PATH] [-o OUT_PATH]
>                          [--java_generate_equals_and_hash]
>                          [--cc_enable_arenas] [--include_imports]
>                          [--include_source_info]
>                          {cpp,csharp,go,java,javanano,js,objc,python,ruby}
> 
> positional arguments:
>   {cpp,csharp,go,java,javanano,js,objc,python,ruby}
>                         language to pass to protoc
> 
> optional arguments:
>   -h, --help            show this help message and exit
>   -p PROTOC_PATH, --protoc_path PROTOC_PATH
>                         path to protoc
>   -o OUT_PATH, --out_path OUT_PATH
>                         output path for protoc
>   --java_generate_equals_and_hash
>                         generate Java's .equals() and .hashCode()
>   --cc_enable_arenas    enable C++ arena allocation
>   --include_imports     include imports in .desc file
>   --include_source_info
>                         do not strip source code info from .desc file

### CODE REVIEW

**Comment by rastapasta** [comment]
wooow, nice work! could you add an info to the README as well for when pretty output should be preferred over normal output (or vice versa)? thanks for your contribution!

**Comment by brandc87** [comment]
I can't get this to run,

`Exception: Can only combine proto files in the same package.`

**Comment by ghost** [comment]
The part generating the error was legacy code, I fixed that now and improved the error message. But it still worked somehow and the error is correct: the .proto file POGOProtos/src/POGOProtos/Networking/Envelopes/Signature.proto has the package POGOProtos.Networking.Signature, but should have POGOProtos.Networking.Envelopes to make the merging of the .proto files possible.

**Comment by AeonLucid** [comment]
@ehoepfner I get `Studio: No such file or directory` when running `python compile_pretty.py csharp`, am I doing something wrong?

**Comment by ghost** [comment]
Isn't that a Visual Studio error?

And on another note: could you please merge without losing the history of the branch you merged from. Because now I cannot fast-forward my branch to the current version and would either have to merge into my branch, that would make much sense, or hard reset my branch, and that messes up the pull requests etc.

**Comment by AeonLucid** [comment]
You mean merge instead of squash? Sorry will do in the future. @ehoepfner

**Comment by ghost** [comment]
@AeonLucid Thanks. I hard reset by branch and I expected this pull request to get messed up, but it didn't. Somehow, github still knows about the commits although they are not part of any history now.

**Comment by AeonLucid** [comment]
https://github.com/AeonLucid/POGOProtos/issues/175

**Comment by brandc87** [comment]
Still getting:
`Exception: Can only combine proto files in the same package.`

Even after "POGOProtos/src/POGOProtos/Networking/Envelopes/Signature.proto has the package POGOProtos.Networking.Signature, but should have POGOProtos.Networking.Envelopes to make the merging of the .proto files possible."

Is there another proto using the wrong package?

**Comment by ghost** [comment]
@mythicaldog That's an old error message. Make sure you are on the current branch.

**Comment by AeonLucid** [comment]
@ehoepfner Is this expected output?

http://image.prntscr.com/image/865910ce44da470dbb1f91091e643025.png

Is there a way to not have the `.proto` and `.cs` in the same directory?

**Comment by ghost** [comment]
@AeonLucid Yes, it is intended. No specific reason other than it is all in one place. It can be easily changed though, if there is a good reason to have it split.

**Comment by AeonLucid** [comment]
@ehoepfner I don't see how it could be useful to have them mixed up. I can't easily copy and paste all the generated files into a project without copying the unnecessary files, now I have to manually remove the `.proto` files.

**Comment by ghost** [comment]
@AeonLucid Ok, but why would need to delete the proto files? Sure, you might not need them, but they will not cause a problem either. I am going add an option for deleting the proto files after the code generation.

**Pull request merged**
