### PR TITLE
Found where that lil bitch Altitude was hiding, add unknown18 and name it, name unknown20 in locationfix

### PR DESCRIPTION
**Pull request by Grover-c13**
float altitude = 4 in location fix, usually between -20 to -30 for my location.

### CODE REVIEW

**Comment by Grover-c13** [comment]
Confirmed with sensor readings.

**Comment by Grover-c13** [comment]
Seems to be the case for IOS too, if anyone else can confirm that would be great

**Comment by Grover-c13** [comment]
Unknown20 = device course, courtesy of @marcel,
Also added unknown18 and trying to confirm it is device speed. Also refactors comments a little.

**Comment by Grover-c13** [comment]
Unknown18 is device speed in m/s

**Comment by Noctem** [comment]
I can confirm from MITMing that this is the right altitude field.

**Pull request merged**
