### PR TITLE
Fix typos in gym-related messages

### PR DESCRIPTION
**Pull request by laverdet**
Some nitpicky typos here that bit me.

### CODE REVIEW

**Comment by laverdet** [comment]
Actually all the battle-related messages are in pretty bad shape. I'll resubmit when I have something fully working.

**Comment by laverdet** [comment]
Nevermind, this PR is actually good. I've gotten gym battles working correctly with the existing message format, the only wrong is the misleading attribute names fixed in this patch.

**Comment by rubenvereecken** [comment]
If you don't mind I'm going to try and keep this one for `v2.0`, or whatever version I dare use for breaking refactorings.

**Comment by laverdet** [comment]
Sure.

**Comment by laverdet** [comment]
Hey this one is actually still relevant ;)

**Comment by AeonLucid** [comment]
Thanks @laverdet 👍

**Comment by XueweiHan** [comment]
Sorry, not sure is this the right place to ask question?
I think I can successfully start a gym battle, but I don't know how to send battle actions. I always get invalid battle actions response. Can you help to understand which field I need to fill for the BattleAction?

**Pull request merged**
