### PR TITLE
StatusCode + PlatformRequest

### PR DESCRIPTION
**Pull request by Grover-c13**
StatusCode + PlatformRequest

### CODE REVIEW

**Comment by Grover-c13** [comment]
- Created StatusCode enum for all known status codes PR #36 
- Created Package for Platform, with subpackage Requests and Responses (metarequests #202)
- Removed unknown6 envelope & response  (metarequests #202)
- Created PlatformRequest messages & responses  (metarequests #202)
- created PlatformRequestType enum

Requests:
- BuyItemAndroidRequest
- BuyItemPokeCoinsRequest
- SendEncryptedSignatureRequest

Responses:
- BuyItemAndroidResponse
- BuyItemPokeCoinsResponse
- GetStoreItemsResponse
- SendEncryptedSignatureResponse

**Comment by Grover-c13** [comment]
Still yet to test these changes as an implementation, some of the semantics have changed (unknown6 having a byte type instead of u2).

Please dont merge til i check

**Comment by Grover-c13** [comment]
This is good to go, tested with JavaAPI and can get pokestops etc

**Comment by Grover-c13** [comment]
Any thoughts anyone?

**Comment by iGio90** [comment]
+1

**Comment by rastapasta** [comment]
+💯    just for the archive, discussion also [here](https://talk.pogodev.org/d/30-unknown6-structure-naming-currently-dubbed-meta-requests)

amazing that u/community figured that out!

**Comment by rastapasta** [comment]
@AeonLucid good to go?

**Comment by AeonLucid** [comment]
@rastapasta Yeahhh, looks good to me.

**Comment by iGio90** [comment]
Merge Simpson!

**Comment by rastapasta** [comment]
Wuhu! 🎉

**Comment by marceloueda** [comment]
Great work! I guess there's a typo in the package for GetStoreItemsResponse (https://github.com/AeonLucid/POGOProtos/blob/master/src/POGOProtos/Networking/Platform/Responses/GetStoreItemsResponse.proto#L2)

**Comment by Grover-c13** [comment]
Yes sorry! you are right

**Comment by marceloueda** [comment]
By the way, is there no GetStoreItemsRequest?

**Comment by Grover-c13** [comment]
The request takes no arguments, so just send the type with null bytes

**Pull request merged**
