### PR TITLE
Update RequestEnvelope

### PR DESCRIPTION
**Pull request by alex89200**
Rename unknown12 to time_since_startup_ms in Networking.Envelopes.RequestEnvelope

### CODE REVIEW

**Comment by rubenvereecken** [comment]
I've known this to be -1, so what's up with that.

**Comment by alex89200** [comment]
This value changes in every request. Try to measure time from the starting of the game till sending the request and unknown12 will be equal to this time in ms.

**Comment by Lennix** [comment]
It's not time_since_startup_ms. This is minutes after starting the app:   unknown12: '741'. This is a few packets in: unknown12: '3068'

**Comment by alex89200** [comment]
Check the difference in unknown12 between subsequent requests and then check the time difference between those requests.
For example:
- the first request was sent at 11:52.  unknown12 is 741  (for example)
- the next request was sent at 11:54.  unknown12 will be ~2741  because the delay between these requests is 2sec that equal to 2000ms.
  etc.

**Comment by mugabe** [comment]
So it's not time_since_startup but time_after_prevous_request.

**Comment by alex89200** [comment]
No :) This value is being increased from request to request. So it will be  (for example):  123, 2321, 3443, 6433, 10332, 15987, etc.

**Comment by drakbar** [comment]
So its delta time...

uk12 += time since startup - time since last request

**Comment by av-tapcore** [comment]
No.
If write it in your terms, it will be:
uk12 += time since last request
that's equal to time since startup.

**Comment by alex89200** [comment]
No.
If write it in your terms, it will be:
uk12 += time since last request
that's equal to time since startup.

**Comment by dmadisetti** [comment]
Has anyone else confirmed this? I haven't had a MITM since they started pinning

**Comment by cstrachan88** [comment]
I'll be able to confirm this Thursday if someone else hasn't by then.

**Comment by trisk** [comment]
The `unknown12` field does not appear to be monotonically increasing in my logs:

```
1470696994377 request_id: '4976630227087130633', unknown12: '1888'
1470697006420 request_id: '4976630227087130633', unknown12: '1108'
1470697006965 request_id: '4976630227087130633', unknown12: '1747'
1470697008122 request_id: '5101309567162122250', unknown12: '824'
1470697008986 request_id: '6696938944677806091', unknown12: '1688'
```

Note this was a new login and the first request included GetPlayer and was retried twice.

**Comment by Grover-c13** [comment]
This should be closed #203, it is int64 ms_since_last_locationfix = 12;

**Comment by rastapasta** [comment]
solved via #203  - thanks for the lively discussion about it and the PR in the first place!

**Pull request closed without merging**
