### PR TITLE
Add app_version to GetPlayerMessage

### PR DESCRIPTION
**Pull request by cyraxx**
This seems to be a new field that the app is sending now. It contains a string such as "0.31.1".

### CODE REVIEW

**Comment by BoBeR182** [comment]
Does this fix https://github.com/AeonLucid/POGOProtos/issues/131 ?

**Comment by cyraxx** [comment]
No, but it's something else that changed.

**Comment by rubenvereecken** [comment]
Cool, useful. Do you mind adding a comment right before the field explaining the string format? Just add something like you said here

> It contains a string such as "0.31.1".

**Comment by cyraxx** [comment]
Sure, like this? 😃

**Comment by rubenvereecken** [comment]
Thanks!

**Pull request merged**
