### PR TITLE
Opinionated rewrite of message names

### PR DESCRIPTION
**Pull request by rubenvereecken**
I want to build this PR as I go, changing names to things that make sense and simplifying wherever I go. This is projected for `v1.3`, we're at `v1.1` at time of writing.

Feedback is welcomed and encouraged.

### CODE REVIEW

**Comment by rubenvereecken** [comment]
@rastapasta, @AeonLucid, it's about ready to have a look. Don't mind the build errors, it's about the general gist. Definitely check out `Networking`.

Also it's really no shame for a submessage to live in the same file (Unknown6), that's what it's for.

**Comment by rubenvereecken** [comment]
Alright we need to have a serious talk about enums. What's up with having their value names prefixed with the enum name? I don't go around saying `COLOR_YELLOW`. A lot of enums do this and it prevents any enums from having values in common, which some will have. For libraries using strings instead of int values of enums, this is great.

Also it makes more sense to say `Item.POKEBALL` than `Item.ITEM_POKEBALL`. Right?

**Comment by rubenvereecken** [comment]
Alright looks like I found out why we have the horrible enum names, they have to be unique within a namespace so can't have too many UNSETs. Most of the rest still stands though.

**Comment by tjhorner** [comment]
I like this PR. The enums and general structure of this have been annoying me a little (I re-structured it myself locally, but didn't think it was PR-worthy heh)

**Comment by AeonLucid** [comment]
Please let me know if this is still relevant.

**Pull request closed without merging**
