### PR TITLE
Add missed features - (2.24.0 - 0.97.2 - 1.67.2)

### PR DESCRIPTION
**Pull request by Furtif**
add gyms battle features
add raid attack features
add lobby features
update protobuf to 3.5.1
update to 0.97.2 (2.24.0)

### CODE REVIEW

**Comment by niicojs** [comment]
You are including stuff like SignalLog that's already here but named Signature

**Comment by Furtif** [comment]
ok delete

**Comment by jmslagle** [comment]
I think on initial glance this looks good @AeonLucid

**Comment by M3G4THEKING** [comment]
Tested and works fine.Ready to go @AeonLucid

**Comment by celandro** [comment]
@AeonLucid are you going to merge or is this project abandoned? Last commit was September

**Comment by apavlinovic** [comment]
@AeonLucid please merge.

**Comment by celandro** [comment]
I think we can safely consider this project abandoned at this point. I have already moved the Java repo over to furtif's fork.  Thoughts?

**Comment by Furtif** [comment]
@celandro uses https://github.com/Furtif/POGOProtos allright
or
java api to uses mine protos repo https://github.com/Furtif/PokeGOAPI-Java/tree/new_updated

**Pull request closed without merging**
