### PR TITLE
Unk25 no longer unk

### PR DESCRIPTION
**Pull request by iGio90**

### CODE REVIEW

**Comment by iGio90** [comment]
int64 unknown25 = 25; // for 0.33 its static -8537042734809897855 or 0x898654dd2753a481, generated via xxHash64("\"b8fa9757195897aae92c53dbcf8a60fb3d86d745\"".ToByteArray(), 0x88533787)

2016082200 (0.33 version code) sha1 hash = b8fa9757195897aae92c53dbcf8a60fb3d86d745

**Comment by Grover-c13** [comment]
Nice

**Comment by iGio90** [comment]
:)

**Comment by AbandonedCart** [comment]
xxHash64(`echo versionCode | sha1sum`.ToByteArray(), 0x88533787)

**Comment by Kermel** [comment]
good job :).

how exactly is the version encoded?
trying "0.33", but sha1 hash of this is "21ab0656c4357f4201e5470485ae0020147fe2e5" (what is the exact input for the mentioned hash "b8fa9757195897aae92c53dbcf8a60fb3d86d745" ?)

**Comment by FabianTerhorst** [comment]
0.33.0 = 2016080700

**Comment by FabianTerhorst** [comment]
0.35.0 = 2016082200

**Comment by Kermel** [comment]
I see, thanks for explanation about the version numbering

However hashing 2016082200 by sha1 produces still something different: "18e53dfcd47b052f28ac7354e2521b8d718b40b5"
(tried for example here: http://www.sha1-online.com/ or here http://hash.online-convert.com/sha1-generator)
:-(

**Comment by rastapasta** [comment]
Beautiful - thanks for figuring it out and bringing it into the protos! 🍺 
@Kermel check @LoungeKatt's example how to xxhash it.

**Comment by mrseeker** [comment]
@Kermel Maybe because you are using SHA1 and not xxhash64? Its a totally different method of hashing...

**Comment by Kermel** [comment]
I don't think this is a problem, sha1 hash should be input to the xxhash64  (as indicated by @iGio90 post with the piece of code) i.e. sha1 should be one of the 2 inputs to the xxhash64 if I am correct.

**Comment by triddin** [comment]
@Kermel I don't get it either...

```
$ versionCode=2016080700
$ echo $versionCode | sha1sum
f4a93f2d011350264d047e20e0b6ccaa86adc4f4  -
$ echo -n $versionCode | sha1sum
bda3f7c03cf14d9adb38aa75ad81f1aafccd25af  -
```

none of these are `b8fa9757195897aae92c53dbcf8a60fb3d86d745`

**Comment by FabianTerhorst** [comment]
you are using macOs right? The sha1 is wrong there.

**Comment by triddin** [comment]
Yup, I also get the same result from ubuntu though.

**Comment by elfinlazz** [comment]
unknown25 = xxHash64("sha1 hash", 0x88533787);
sha1 hash is static string(including double qoutes) that exist inside client.
0.33.0 = "b8fa9757195897aae92c53dbcf8a60fb3d86d745"
0.35.0 = "0f15301fe1d0e824738ef5d93355e56a6fb910d4"
idk how they are generated, they're already hashed as static string.
so we can't sure unknown25 is versioncode, maybe, but not sure

**Comment by mjmjelde** [comment]
@FabianTerhorst @iGio90 The sha1 hash of 2016082200 = 18e53dfcd47b052f28ac7354e2521b8d718b40b5  Tested this with multiple sha1 hash sites as well.  How exactly did you get b8fa9757195897aae92c53dbcf8a60fb3d86d745 from it?

**Comment by FabianTerhorst** [comment]
@mjmfighter we are talking about 0.33.0 2016080700

**Comment by triddin** [comment]
@elfinlazz So basically it's still unk25... we're just guessing that it's a version code because it's a baked in string that changes each version?

**Comment by FabianTerhorst** [comment]
2016080700 is the version code and 0.33.0 is the version name

**Comment by mjmjelde** [comment]
@FabianTerhorst ok?  The hash of that is still bda3f7c03cf14d9adb38aa75ad81f1aafccd25af which is not what its suppose to be. (and the first post is wrong because it says 2016082200 is 0.33)

**Comment by FabianTerhorst** [comment]
https://github.com/AeonLucid/POGOProtos/pull/208#issuecomment-242040062 ?

**Comment by iGio90** [comment]
Im also getting another sha1 from the websites im using, Fabian somehow reach it from the version code and make a commit on Java api, maybe you would mind to share the way you reached it? Convo is and commit is here:
https://github.com/Grover-c13/PokeGOAPI-Java/pull/650

**Comment by Kermel** [comment]
Well, so tu sum the discussion up:
1) We know how the Unknown25 is populated - it is xxHash64("<some sha1 hash including quotes>".ToByteArray(), 0x88533787)
2) We know the values of the "some sha1 hash including quotes" - it exists as a static string somewhere in the client and we currently know the value for version 0.33 and version 0.35 of the app
3) We have no bloody idea how is this sha1 hash calculated (what is the input)

Right ? :)

**Comment by triddin** [comment]
@mjmfighter in [his comment](#issuecomment-242054145) @elfinlazz explains that the sha1hash value is a string  that's compiled into the executable, which includes double-quotes around it and which nobody seems to know how to generate (apart from maybe @FabianTerhorst). It may or may not be a version string, however it does change with each version.

**Comment by FabianTerhorst** [comment]
The version code is inside of the manifest from the pokemon go app. Its the unique id for every version.

**Comment by elfinlazz** [comment]
@Kermel exactly

**Comment by mjmjelde** [comment]
@triddin I know that.  I know how the final value is compiled.  I was just using the value from the first post and trying to compare wrong values.  I'm just curious as to how @FabianTerhorst got the hashed value to go into the xxHash64 function.  Like, give us a formula on how you computed it or something

**Comment by triddin** [comment]
@mjmfighter From reading over [here](https://github.com/Grover-c13/PokeGOAPI-Java/pull/650#issuecomment-242031192) I'm not sure they did solve it, I think maybe they got confused and started patting each other on the back and assumed it was solved?

**Comment by iGio90** [comment]
Wait, he also did a commit based on what he find. Can you just test it?

**Comment by FabianTerhorst** [comment]
I tested it and it doesn´t return the right value thats why asked "realy?"

**Comment by iGio90** [comment]
FabianTerhorst 
commented about 2 hours ago
But i had never looked into the version code without you.

This was supposed that you get it no? Otherwise we need some english lessons here. 

#revert please -.- sorry for the misunderstood

**Comment by triddin** [comment]
@FabianTerhorst @iGio90  It's easy to have miscommunications, thankfully @Kermel was keeping an eye out :)

**Comment by Kermel** [comment]
Well so it still remains Unknown25 and with every version we must figure out its value.
So for current version (0.35.0) the value for this field is "7363665268261373700" right ?

**Comment by Kermel** [comment]
And maybe more important - is there an "easy" way how to find the sha1 value (in quotes) that is used as an input for the xxHash64 somewhere in the apk ?

**Comment by iGio90** [comment]
We are back on it. Im still sure version code is involved. Vcode + something else.

**Comment by elfinlazz** [comment]
@Kermel hashed code static string inside client so we can't find out in client...cuz there is no input...

**Comment by iGio90** [comment]
Im not at home because of the damn eartquackes here in italy. I'll try to disass and look for anything that uses version code. In anycase its inside

**Comment by j16sdiz** [comment]
Ingress have the git commit id (sha1) in the version code. Might be the same for pogo.

**Comment by trisk** [comment]
@j16sdiz the commit ID being embedded by their build system is an extremely convincing explanation. That would let them track development builds without having to bump the DownloadSettings version.

**Comment by iGio90** [comment]
@trisk @j16sdiz maybe. But if so, it must be hardcoded somewhere no?

**Comment by trisk** [comment]
It'd be a preprocessor macro in the source and use a definition passed with `-D` or from a generated header.

**Comment by FabianTerhorst** [comment]
Its not a constant in the BuildConfig https://github.com/FabianTerhorst/PokemonGo/blob/master/java/com/nianticlabs/nia/BuildConfig.java

**Comment by iGio90** [comment]
it must be in the so since it's the same on ios and android

**Comment by trisk** [comment]
@FabianTerhorst  This is in the native code (C++), not Java.

**Comment by FabianTerhorst** [comment]
Would be to easy when it wouldn´t.

**Comment by iGio90** [comment]
Did anyone try to search for the sha1 of the 0.33 in IDA? i didn't find it hardcoded with Hopper

**Comment by iGio90** [comment]
and also, did anyone already reversed the sha1 of the 0.35?

**Comment by trisk** [comment]
The 0.35.0 xxHash64 input string is `"0f15301fe1d0e824738ef5d93355e56a6fb910d4"`. The strings in the binary are obfuscated it's easier to see them at runtime.

**Comment by iGio90** [comment]
but anyway, even if this is the sha1 code of the commit. We don't need to know anything else. It's just a metter of naming the unk value since we can hardcode the encrypted value within our requests

**Comment by trisk** [comment]
VersionStringHash? :smile:

**Comment by iGio90** [comment]
@trisk imho, we should wait the next PoGo version to check if it will change again. Maybe anyone can check the version before 0.33? unk6 is up since the first version, so that.. unk25 should be different for each release. If so, VersionStringHash is superfine 👍

**Comment by iGio90** [comment]
i'll do it now :P
- ahh forced update.. well, just wait to see if it change on the next release and let's name as you said. Im almost sure it will change once again

**Comment by trisk** [comment]
Does an old version still send the initial GetPlayer before getting kicked out? That should be enough.

Also I suspect NianticLabsPlugin is managed in a separate repo from the game client, which would mean this is actually specific to the NianticLabsPlugin version rather than the app version.

**Comment by iGio90** [comment]
No it doesn't fire the getPlayer. There is not signature building

**Comment by alexthepink95** [comment]
so if 0.33 was -853704273480989785 what is 0.35

**Comment by Grover-c13** [comment]
7363665268261374000

**Comment by elfinlazz** [comment]
@Grover-c13 7363665268261373700

**Comment by Grover-c13** [comment]
Looks like i have precision issues :D

**Comment by Kermel** [comment]
Does anyone already found out whats the actual value for the new version of the game ?

**Pull request merged**
