### PR TITLE
Add packed attributes to CaptureProbability

### PR DESCRIPTION
**Pull request by cyraxx**
Another fix for protobuf.js users

### CODE REVIEW

**Comment by rastapasta** [comment]
Just to make you aware: this is a bug in protobuf.js (https://github.com/dcodeIO/protobuf.js/issues/432) - we should make the protos syntax3 conform (all repeated fields are packed by default) again as soon as they got it fixed.

also @cyraxx, check out the hot fix for protobufjs https://github.com/dcodeIO/protobuf.js/issues/432#issuecomment-234751163
Cheers!

**Comment by cyraxx** [comment]
Ah, thanks @rastapasta, I was not aware of that! I was wondering why protobuf.js needs all these packed attributes while other implementations don't seem to care.

I hope protobuf.js is going to fix this as I don't really see a good/clean way to incorporate a patch into [node-pogo-protos](https://github.com/cyraxx/node-pogo-protos).

**Comment by rastapasta** [comment]
@cyraxx ah funny, working on the same thingy 💃  [pokemon-go-protobufjs-node](https://github.com/rastapasta/pokemon-go-protobufjs-node) - currently solved the issue by forking protobuf.js and incoperating the fix. additionally working on a enum->value mapper. all soon to be done ;)

**Comment by justinleewells** [comment]
@rastapasta You are a saint. This should help with users on Windows so much. Are you planning on adding pokemon-go-protobufjs-node to pokemon-go-mitm?

**Comment by cyraxx** [comment]
@rastapasta Haha, neat! I've also briefly looked into how to extend protobuf.js or the compiled messages to easily convert enum values back to names but ended up just doing [this](https://github.com/cyraxx/pogobuf/blob/master/example.js#L116) instead.

Honestly with all the effort you're putting into it, I might just ditch my node-pogo-protos module and switch [pogobuf](https://github.com/cyraxx/pogobuf) over to yours!

**Comment by rastapasta** [comment]
@justinleewells that's the aim, yeah! would love to get away from the compilation hassle!
@cyraxx let's see what the day will bring :-)

**Comment by rastapasta** [comment]
just FYI: still having some issues - so this is WIP, but its a protobuf.js day for me :)

**Comment by justinleewells** [comment]
Either way, it's good to know that you're working on it. Thanks for all the work you're putting in, man.

**Comment by cyraxx** [comment]
FYI here's the workaround I've come up with: https://github.com/cyraxx/node-pogo-protos/commit/17b597513cb8c7aab777cd1ea5fe7228cd15c166

**Pull request merged**
