### PR TITLE
Fields in AndroidGpsInfo are in fact packed.

### PR DESCRIPTION
**Pull request by iphydf**

### CODE REVIEW

**Comment by tanis2000** [comment]
No need to add that. Packed is the default with proto3

**Comment by iphydf** [comment]
I agree, but there is a bug in proto-lens (google/proto-lens#38) that makes this necessary. Until that bug is fixed, this is needed, and it doesn't harm other generators.

**Comment by Grover-c13** [comment]
It will also help with backwards compatibility for people (for whatever reason) using proto2.

**Comment by laverdet** [comment]
There's 68 packable repeated fields in the protos and only 10 of them are marked packed. I feel like we should have a clear policy of explicitly marking [packed=true] or not and being consistent about it because otherwise these PR's will keep on coming.

```
$ grep -R repeated . | egrep 'float|int32|int64|fixed64|bool|Enums|ItemId' | wc -l
      68
$ grep -R repeated . | egrep 'float|int32|int64|fixed64|bool|Enums|ItemId' | grep packed | wc -l
      10
```

**Comment by iphydf** [comment]
I'll just make this part of my preprocessing step, using `sed` to add `packed` to all repeated scalar numeric fields. So I would suggest we remove all redundant `packed`.

**Pull request closed without merging**
