### PR TITLE
SensorInfo is repeated

### PR DESCRIPTION
**Pull request by laverdet**
_monocle pops off face_

### CODE REVIEW

**Comment by laverdet** [comment]
I would guess that `AndroidGpsInfo` is repeated as well but my Android is dead right now. Seems like the app takes snapshots of sensor and location data every so often and then stuffs them in `Signature` in batch w/ the next request.

**Comment by wchill** [comment]
Dumps don't seem to match up with this.

**Comment by laverdet** [comment]
It's possible that this changed in one of the later versions, as I can't seem to reproduce the repeated field right now on 0.33.0.

I have tons of raw requests + responses saved from the original 0.29.0 client on iOS. This was before SSL-pinning was implemented so I'm paying special attention to these dumps now because I suspect the app is somehow communicating to the server when it detects a jailbroken iPhone, and these are the only dumps I'll ever see from a non-jailbroken iOS device.

Anyway, now that we can read key6 on these old dumps I went back and reanalyzed them and discovered that the majority had repeated SensorInfo data. Below is one of those dumps.

Perhaps they scaled back transmission of SensorInfo to save client bandwidth.. I'm not sure. It's definitely something we should keep an eye out for though.

```
[redacted]
key[7] ~= [Blob{145}]
    key[1] = [Varint: {d4c2 3e} - 512170 OR 1024340]
    key[3] = [64bit {000000006ea1773f} - 0.005769185721874237]
    key[4] = [64bit {00000000403d97bf} - -0.02269458770751953]
    key[5] = [64bit {00000000bf55fabf} - -1.6459341049194336]
    key[6] = [64bit {000000a099d589c0} - -826.7000122070312]
    key[7] = [64bit {0000004033cb84c0} - -665.4000244140625]
    key[8] = [64bit {000000e0cc6c5a40} - 105.70000457763672]
    key[10] = [64bit {00000040c631aa3f} - 0.05116099864244461]
    key[11] = [64bit {00000040ed29bdbf} - -0.11392100155353546]
    key[12] = [64bit {000000a0a3aaecbf} - -0.895829975605011]
    key[13] = [64bit {000000000b74613f} - 0.002130528911948204]
    key[14] = [64bit {000000000b74713f} - 0.004261057823896408]
    key[15] = [64bit {000000000b74513f} - 0.001065264455974102]
    key[16] = [64bit {000000203c14ab3f} - 0.05288875475525856]
    key[17] = [64bit {0000006041580340} - 2.41809344291687]
    key[18] = [64bit {00000080e5012340} - 9.503704071044922]
    key[19] = [Varint: {03} - -2 OR 3]
key[7] ~= [Blob{136}]
    key[1] = [Varint: {dde9 3e} - -514671 OR 1029341]
    key[3] = [64bit {00000000009453bf} - -0.0011949539184570312]
    key[4] = [64bit {0000000088c6acbf} - -0.05620217323303223]
    key[5] = [64bit {00000000d0cebdbf} - -0.11643695831298828]
    key[6] = [64bit {000000a099e189c0} - -828.2000122070312]
    key[7] = [64bit {000000a099c584c0} - -664.7000122070312]
    key[8] = [64bit {0000000000805e40} - 122]
    key[10] = [64bit {000000000aa0a83f} - 0.04809600114822388]
    key[11] = [64bit {000000a0bd4fbdbf} - -0.11449799686670303]
    key[12] = [64bit {00000080cdabecbf} - -0.8959720134735107]
    key[13] = [64bit {000000000b7461bf} - -0.002130528911948204]
    key[15] = [64bit {00000040138b7ebf} - -0.007456851191818714]
    key[16] = [64bit {000000e075cebc3f} - 0.1125253364443779]
    key[17] = [64bit {000000a0e0500340} - 2.4144909381866455]
    key[18] = [64bit {000000a019022340} - 9.504101753234863]
    key[19] = [Varint: {03} - -2 OR 3]
key[7] ~= [Blob{145}]
    key[1] = [Varint: {e890 3f} - 517172 OR 1034344]
    key[3] = [64bit {000000802a0591bf} - -0.016621269285678864]
    key[4] = [64bit {000000000008453f}]
    key[5] = [64bit {0000000010feb4bf} - -0.0820016860961914]
    key[6] = [64bit {000000e0cce089c0} - -828.1000366210938]
    key[7] = [64bit {000000a099c184c0} - -664.2000122070312]
    key[8] = [64bit {0000000000405e40} - 121]
    key[10] = [64bit {000000a03c81a83f} - 0.047860998660326004]
    key[11] = [64bit {0000006093fcbcbf} - -0.11322899907827377]
    key[12] = [64bit {00000060f7abecbf} - -0.8959919810295105]
    key[13] = [64bit {000000000b74713f} - 0.004261057823896408]
    key[14] = [64bit {000000000b7461bf} - -0.002130528911948204]
    key[15] = [64bit {000000000b7461bf} - -0.002130528911948204]
    key[16] = [64bit {000000c0e047bb3f} - 0.10656552016735077]
    key[17] = [64bit {000000407d1f0340} - 2.3903756141662598]
    key[18] = [64bit {0000006041052340} - 9.51026439666748]
    key[19] = [Varint: {03} - -2 OR 3]
key[7] ~= [Blob{136}]
    key[1] = [Varint: {f1b7 3f} - -519673 OR 1039345]
    key[3] = [64bit {00000000964f73bf} - -0.004714570939540863]
    key[4] = [64bit {00000000c03872bf} - -0.004448652267456055]
    key[5] = [64bit {0000000000e9babf} - -0.1051177978515625]
    key[6] = [64bit {000000e0ccec89c0} - -829.6000366210938]
    key[7] = [64bit {0000000000b484c0} - -662.5]
    key[8] = [64bit {000000e0cc8c5e40} - 122.20000457763672]
    key[10] = [64bit {000000a06a82a83f} - 0.04786999896168709]
    key[11] = [64bit {00000080ca31bdbf} - -0.11404100060462952]
    key[12] = [64bit {000000e019a6ecbf} - -0.8952760100364685]
    key[14] = [64bit {000000000b74713f} - 0.004261057823896408]
    key[15] = [64bit {000000000b74713f} - 0.004261057823896408]
    key[16] = [64bit {0000006027e3bd3f} - 0.11674734205007553]
    key[17] = [64bit {000000800e3c0340} - 2.404324531555176]
    key[18] = [64bit {000000c064032340} - 9.506628036499023]
    key[19] = [Varint: {03} - -2 OR 3]
key[7] ~= [Blob{136}]
    key[1] = [Varint: {fede 3f} - 522175 OR 1044350]
    key[3] = [64bit {00000000c86f95bf} - -0.020934224128723145]
    key[4] = [64bit {00000000f033b1bf} - -0.0671987533569336]
    key[5] = [64bit {00000000209fc8bf} - -0.19235610961914062]
    key[6] = [64bit {000000a099e589c0} - -828.7000122070312]
    key[7] = [64bit {0000000000c084c0} - -664]
    key[8] = [64bit {000000a099595e40} - 121.4000015258789]
    key[10] = [64bit {000000c05983a73f} - 0.045924000442028046]
    key[11] = [64bit {000000e07283bdbf} - -0.11528699845075607]
    key[12] = [64bit {00000000bda9ecbf} - -0.8957200050354004]
    key[13] = [64bit {000000208fff97bf} - -0.023435818031430244]
    key[14] = [64bit {000000c04b8b923f} - 0.01810949668288231]
    key[16] = [64bit {00000020084dc43f} - 0.1586008220911026]
    key[17] = [64bit {000000e086470340} - 2.4099252223968506]
    key[18] = [64bit {000000605b022340} - 9.504603385925293]
    key[19] = [Varint: {03} - -2 OR 3]
[redacted]
```

**Comment by AeonLucid** [comment]
It's repeated now in the current protos.

**Pull request closed without merging**
