### PR TITLE
Update for 0.35.0 n minor fix

### PR DESCRIPTION
**Pull request by elfinlazz**

### CODE REVIEW

**Comment by trisk** [comment]
Shouldn't the type be `.POGOProtos.Enums.PokemonId` for Pokémon IDs? Or are there values outside that range?

**Comment by trisk** [comment]
@elfinlazz clarified that this is an array of counters indexed by type, thanks. For unk12, would `time_since_last_locationfix_ms` fit the existing name pattern better?

**Comment by gionata-bisciari** [comment]
I can't wait for this to be merged ç_ç

**Comment by AeonLucid** [comment]
Looks good! :+1: 
Thank you for your work with updating the protos.

**Pull request merged**
