### PR TITLE
Resolved issue #110, int64 is correct

### PR DESCRIPTION
**Pull request by BornSupercharged**

### CODE REVIEW

**Comment by rubenvereecken** [comment]
Dammit. I've never investigated this myself but I keep seeing back-and-forts PRs. Are some protobuf implementations simply not unpacking the data correctly?

Yo @Grover-c13 step in and check it out. Also #110

**Comment by Grover-c13** [comment]
can not get it working with fixed64 in java. It is strange that most work with fixed64 except for this one for java. i assume youre using PHP simplyphp?

**Comment by csnewman** [comment]
The data type might not be either of these two. Protobuf is designed that you can swop out certain types for others and it will try its best.

From https://developers.google.com/protocol-buffers/docs/proto#updating
int32, uint32, int64, uint64, and bool are all compatible
fixed32 is compatible with sfixed32, and fixed64 with sfixed6

So it could actutally be one of these other types and protobuf is just casting. Has anyone tried the other compatible types?

**Comment by Grover-c13** [comment]
You may be right, i was just checking the original master game file leak (http://pastebin.com/SBdB0VPL) and for some reason its marked as int64 instead of uint64 like most other protos (there is one other exception marked as int64 and thats EggIncubatorProto).

Tested on java  and working as normal int64, can you confirm when you get the chance @simplyphp

**Comment by BornSupercharged** [comment]
I'm using C#, the current value uint64 does not work.

**Comment by Grover-c13** [comment]
Please try int64

**Comment by Grover-c13** [comment]
Just to clarify, in the proto definition :P

**Comment by BornSupercharged** [comment]
Right, this will take me a few minutes

**Comment by BornSupercharged** [comment]
Resolved with int64.

**Comment by BornSupercharged** [comment]
Updated my commit.

**Comment by Grover-c13** [comment]
Awesome, mystery solved. please comment it though with a link to this PR or something so people know not to change it.

@rubenvereecken

**Comment by BornSupercharged** [comment]
Done

**Comment by rubenvereecken** [comment]
Eh alright so we're flying with _signed_ integers now? Sure. Happily awaiting your next PR.

**Comment by dmadisetti** [comment]
Suspiciously not signed https://github.com/rubenvereecken/pokemongo-api/issues/93

**Pull request merged**
