### PR TITLE
Added missing fields found by my auto-generation tools

### PR DESCRIPTION
**Pull request by goedzo**
By using my auto generation tool of protofiles, I found some missing fields. Here is the fix for the PR.

### CODE REVIEW

**Review by niicojs — CHANGES_REQUESTED** [review]
you have to use absolute path (.POGOProtos.Data....)

**Review by niicojs — CHANGES_REQUESTED** [review]
I think you are mistaken CheckCodenameAvailable (which is not used anymore I think) and ClaimCodename

**Comment by niicojs** [comment]
Thanks. 
I think only `BattleAttributes` is correct,. `BattleResults.proto` need update and `CheckUsername` is not there anymore I think.

**Comment by niicojs** [comment]
also, please don't commit in a PR all those files that includes absolute address that only works on your cmoputer

**Comment by goedzo** [comment]
@nicoschmitt  yes you are right. There are new messages and fields found that have no message files or .proto references. They need to be fixed by adding them the proper way. My tool only finds them and adds them, but doesn't know how to automatically generate them from the source proto file. Nevertheless, this PR can be used to see what needs to be done to fix things.

The extra files I created to be able to build a docker container that can generate the proto files for Pyhton. Only checked them into my own REPO, so not sure how GH decided to put them here. So there is no need to add them too, but feel free to do it anyway, since it is always cool to have a container that can generate the files :).

**Pull request closed without merging**
