### PR TITLE
change pokemon id to uint64 in NicknamePokemonMessage

### PR DESCRIPTION
**Pull request by pimpcapital**

### CODE REVIEW

**Comment by Grover-c13** [comment]
i really dont think this is correct. The java api has been using fixed64 and working correctly

**Comment by pimpcapital** [comment]
fixed64 fails on python compiled version and uint64 works....
..
can you have a quick check to see if changing it to uint64 breaks on java compiled version

**Comment by Grover-c13** [comment]
it was originally uint64, we changed to fixed64 due to it not working.

**Comment by Grover-c13** [comment]
there is also https://github.com/tejado/pgoapi/issues/59 which is in python i believe that started working correctly after the change.

**Comment by rubenvereecken** [comment]
I'm going crazy. Please check this @beijunyi

**Pull request closed without merging**
