### PR TITLE
More accurate descriptions of the sensor info (based on android names)

### PR DESCRIPTION
**Pull request by mjmjelde**
Updated some of the names in the Sensor Info proto to more accurately describe what they relate to.  Based on the names of the sensors in Android.

### CODE REVIEW

**Comment by trisk** [comment]
There was a PR on the old Unknown6 repo with the similar field names that was lost.
Android uses TYPE_MAGNETIC_FIELD so should `magnetic_x` etc. be `magnetic_field_x`?

**Comment by mjmjelde** [comment]
@trisk yes you are correct.  Updated the magnetic fields to magnetic_field to help clarify them

**Comment by trisk** [comment]
LGTM assuming these have been verified as the SensorManager inputs.

**Comment by mjmjelde** [comment]
I have verified these with both my phones as the inputs I was getting.  If someone else needs to verify these inputs please let do so.

**Comment by Grover-c13** [comment]
Confirming:

Sensor Proto:
"SensorInfo": {
"TimestampSnapshot": 59036,
"MagnetometerX": 0.0022337138652801514,
"MagnetometerY": 0.0026361793279647827,
"MagnetometerZ": 0.2616863250732422,
"AngleNormalizedX": 21.540000915527344,
"AngleNormalizedY": 21.899999618530273,
"AngleNormalizedZ": 52.560001373291016,
"AccelRawX": -0.00027099999715574086,
"AccelRawY": 0.012594999745488167,
"AccelRawZ": 0.39435499906539917,
"GyroscopeRawX": 0.008522115647792816,
"GyroscopeRawY": -0.008522115647792816,
"GyroscopeRawZ": 0.008522115647792816,
"AccelNormalizedX": -0.2290843278169632,
"AccelNormalizedY": 0.09253333508968353,
"AccelNormalizedZ": 9.803537368774414,
"AccelerometerAxes": 3
},

Sensor Outputs:
Linear Acceleration Sensor [0.0022337139,0.0026361793,0.26168633]
AK09911C Magnetic field Sensor: [21.54,21.9,52.56]
Rotation: [-2.71E-4,0.012595,0.394355,0.918871,3.0]
Gyroscope: [0.008522116,-0.008522116,0.008522116]
Gravity: [-0.22908433,0.092533335,9.803537]

**Comment by laverdet** [comment]
Oh this makes so much sense. Great work!

key9 is also present in SensorInfo. Perhaps `int32 has_magnetic_field = 9`? In 0.35.0 I've only seen -1 or 1. When key 6-8 are null I see key9 == -1.. if key 6-8 are set then I see 1. In some of my older dumps I've seen 2, but I haven't reproduced that on the current version.

**Comment by Grover-c13** [comment]
Probably Rotation Accuracy:
Rotation: [-2.71E-4,0.012595,0.394355,0.918871,**3.0**]

**Pull request merged**
