### PR TITLE
0.35: getPlayer

### PR DESCRIPTION
**Pull request by iGio90**

### CODE REVIEW

**Comment by iGio90** [comment]
[<-] Request for GetPlayer  { player_locale: { country: 'IT', language: 'it' },

**Comment by rastapasta** [comment]
heyhey @iGio90 - great to see this update!

just for keeping the code base clean, could you change it so that the PlayerLocaleMessage is defined inline instead of a separate file in the .Requests namespace? Its not a singleton request with a response (in the .Response namespace).

Thanks for your contribution! :heart:

**Comment by iGio90** [comment]
Not sure i get you at all @rastapasta 
Do you mean something like that?

**Comment by iGio90** [comment]
@trisk edited as your suggestion. Your second suggestion goes against what @rastapasta ask me then? O.o

**Comment by rastapasta** [comment]
thanks for adapting @iGio90! i +1 the second suggestion of @trisk, having a separate file in the .Data namespace would be fine - was just worried seeing it in .Messages.PlayerLocale - would you mind modifying it that way? cheers and thanks again! 🌻

**Comment by iGio90** [comment]
doing right now

**Pull request closed without merging**
