### PR TITLE
fixed typo in Signature.proto and request envelope

### PR DESCRIPTION
**Pull request by WallyCZ**
Field named Altitude is in real Accuracy (tested on Android)

### CODE REVIEW

**Comment by Grover-c13** [comment]
Thankyou @WallyCZ, we have been trying to work out the strange values for a few days now :P

**Comment by Grover-c13** [comment]
Apparently IOS sends this as well, but not sure where they are getting the info as they dont have anything like radial accuracy (except horizontalAccuracy which is being sent in its own field)

**Comment by WallyCZ** [comment]
It can be probably computed from horizontal accuracy. Depends on how it is defined in iOS, but definition from Android is: https://developer.android.com/reference/android/location/Location.html#getAccuracy()

**Comment by Grover-c13** [comment]
we were discussing it earlier today, currently thinking this altitude field
should be labeled as horizontal accuracy (the definitions are almost
identical for ios and android getAccuracy). As the value range of -1 and 1
does not conform to what is expected for horizontal accurracy on ios.

**Comment by WallyCZ** [comment]
PR Updated by your suggestion

**Comment by Grover-c13** [comment]
any theory on why it sends vertical accuracy since it doesnt seem to send altitude at all?

**Comment by WallyCZ** [comment]
Currently it seems that field Altitude in request envelope is also accuracy. I have this value == 10.0 on real device, which match with value from GPS Api. I am really not 10.0m above sea level :) Values above 1000m stops API giving data, just try it ;)

**Comment by WallyCZ** [comment]
@Grover-c13 Maybe it sends altitude also, but we don't know this field yet... But who knows if it is really vertical accuracy (I can't test it, it is not filled on Android)

**Comment by Grover-c13** [comment]
Yeah maybe, anyway i would say this is looking good. Ty for digging. hopefully someone will merge soon

**Comment by Grover-c13** [comment]
Ive doubled check this with sensor readings from my phone (only the request envelope field) and get matching accuracy values in the dumps + sensor readings. Please merge :D

**Comment by rastapasta** [comment]
confirmed on discord by multiple beautiful people, merging!  thanks for the discussion and the PR! :beer:

**Pull request merged**
